name: Build Android AAB

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build AAB
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run Expo Prebuild
        run: |
          set -e
          export CI=1
          npx expo prebuild --platform android --clean --no-install

      - name: Build Android AAB
        working-directory: android
        run: ./gradlew bundleRelease -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/release.keystore -Pandroid.injected.signing.store.password=7dc43c7d13c2fce97dad4e3aee328dcf -Pandroid.injected.signing.key.alias=d9b9872af962a07364e46ed23b05a360 -Pandroid.injected.signing.key.password=23d2670e47bf2fcea8e2b8d3469073af
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: app-release.aab
          path: android/app/build/outputs/bundle/release/app-release.aab
